
[package]
name = "back-end"
version = "0.1.0"
edition = "2018"
authors = ["Matias Suez <matisuez@gmail.com>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7"
serde_derive = "1.0.130"
rocksdb = "0.17.0"
